### PR TITLE
Add decouple

### PR DESCRIPTION
**Pull request by akatsoulas**

### CODE REVIEW

**Comment by akatsoulas** [comment]
rebased

**Comment by glogiotatidis** [comment]
cool, kill the local_config lines and remove from `.gitignore`

**Comment by akatsoulas** [comment]
done

**Comment by glogiotatidis** [comment]
thanks!

**Comment by glogiotatidis** [comment]
oh shit, this should go in `requirements.txt`

**Comment by glogiotatidis** [comment]
updated here https://github.com/glogiotatidis/veresebot/commit/84c988371d7a93319de7bc40833bafa3fee9701c

**Pull request merged**
